<a href="https://colab.research.google.com/github/caleb-stewart/A-Z_Machine-Learning/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np # Arrays
import pandas as pd # Import data set and matrix features
import matplotlib.pyplot as plt # Allows us to plot charts


## Importing the dataset

In [14]:
# Hold the data.csv data - Dataframe
dataset = pd.read_csv("Data.csv")
print(dataset.columns)


Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')


In [18]:
# Create two entries
# Matrix of features and dependent variable vector

# Features are the columns you use to predit depedndent variable
# Dependent variable is what you want to predict

# Take indexes of rows and columns we want to extract
features = dataset.iloc[:, :-1].values # We get all rows, and all but last column
dep_vars = dataset.iloc[:, -1].values # Only the last column

# Features should only have 'Country, Age, Salary"
print(features)

# dep_vars should only have "Purchased"
print(dep_vars)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [19]:
# Take care of empty columns or rows
# 1. We can ignore observations if we have a large dataset
# 2. We can also replace missing data by assigning the average within the column

# scikit-learn used for data science
from sklearn.impute import SimpleImputer
# New SimpleImputer, that will replace nan with the mean of column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# Replace only the rows with numbers, not text
imputer.fit(features[:, 1:3])
# Apply the transformation. This creates a new copy
features[:, 1:3] = imputer.transform(features[:, 1:3])
# Now all nan are replaced
print(features)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [22]:
# One hot encoding. Turning the country column into three columns
# This envoles creating binary vectors
# This is because our model will have a hard time with Strings and correlation b/w them

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Two arguments:
  # Specify what transformation (kind of transf, kind of encoding, index of cols we want)
  # Remainder; Keep columns we dont want to encode
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# Apply to features array, and force to be np
features = np.array(ct.fit_transform(features))
print(features)

# This makes three new columns, each correlating with a country

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [24]:
# Convert the 'yes' and 'no' to 1s and 0s
from sklearn.preprocessing import LabelEncoder

# Automatically changes yes and no's
le = LabelEncoder()
dep_vars = le.fit_transform(dep_vars)
print(dep_vars)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [25]:
# feature scaling before or after splitting ???
  # after because the test set is supposed to be a brand new set

# We will 4 sets.
  # (feature matrix train, feature matrix test) and (dep var train, dep var test)

from sklearn.model_selection import train_test_split
# 80% train, 20% split
# also fix the random seed, so we always get the same train and test split
feature_train, feature_test, dep_train, dep_test = train_test_split(features, dep_vars, test_size=0.2, random_state=1)



In [30]:
print(feature_train)

(8, 5)


In [27]:
print(feature_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [28]:
print(dep_train)

[0 1 0 0 1 1 0 1]


In [29]:
print(dep_test)

[0 1]


## Feature Scaling

In [31]:
# We do this to avoid some features being dominated by other features

from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # This uses standard deviation (values betwee -3 and 3)

# We dont feature scale our encoding, because they are already in an appropriate range
feature_train[:, 3:] = sc.fit_transform(feature_train[:, 3:])
feature_test[:, 3:] = sc.transform(feature_test[:, 3:])

In [32]:
print(feature_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [33]:
print(feature_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
